# Data paths
data_paths:
  raw_data: data/raw
  processed_data: data/processed
  genes: gene_expressions
  brain_regions_genes_ge: brain_regions_genes_geneexpressions
  analysis: data/analysis
  plots: data/plots

# Ids of donor for ease of access
donors_ids:
  - 9861
  - 10021
  - 12876
  - 14380
  - 15496
  - 15697

