# Data paths
data_urls:
  - https://human.brain-map.org/api/v2/well_known_file_download/178238387
  - https://human.brain-map.org/api/v2/well_known_file_download/178238373
  - https://human.brain-map.org/api/v2/well_known_file_download/178238359
  - https://human.brain-map.org/api/v2/well_known_file_download/178238316
  - https://human.brain-map.org/api/v2/well_known_file_download/178238266
  - https://human.brain-map.org/api/v2/well_known_file_download/178236545

data_paths:
  raw_data: data/raw
  processed_data: data/processed
  output_data: data/output
  genes: gene_expressions
  brain_regions_genes_ge: brain_regions_genes_geneexpressions
  analysis: data/analysis
output_paths:
  stats: stats
  plots: plots

# Ids of donor for ease of access
donors_ids:
  - 9861
  - 10021
  - 12876
  - 14380
  - 15496
  - 15697

